M48
; DRILL file {KiCad 9.0.7} date 2026-04-26T23:33:01-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-26T23:33:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X144.28Y-225.54
X159.28Y-225.54
X178.4Y-225.54
X194.28Y-225.64
T2
X157.1Y-168.65
T3
X141.0Y-167.0
X141.0Y-242.0
X195.0Y-167.0
X195.0Y-242.0
M30
